spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productopolis_dev_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true  # Set to true to show SQL statements in the console for debugging

  kafka:
    bootstrap-servers: cluster.playground.cdkt.io:9092